CREATE TABLE ADDRESS (
    id BIGINT NOT NULL PRIMARY KEY,
    city VARCHAR(30),
    street VARCHAR(30),
    house VARCHAR(30)
);

CREATE TABLE STORE (
    id BIGINT NOT NULL PRIMARY KEY,
    phone VARCHAR(30),
    name VARCHAR(30),
    address_id INT,
    FOREIGN KEY (address_id) REFERENCES ADDRESS (id)
);

CREATE TABLE CLOSURETYPEENUM (
    closureType BIGINT
);

CREATE TABLE CLOSURE (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STORE_ID BIGINT,
    text VARCHAR(30),
    START_DATE DATE,
    END_DATE DATE,
    CLOSURE_TYPE VARCHAR(30),
    FOREIGN KEY (CLOSURE_TYPE) REFERENCES CLOSURETYPEENUM (closureType)
);

CREATE TABLE CHANGELOG (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STORE_ID BIGINT,
    CHANGED_BY VARCHAR(30),
    CHANGE_DATE DATE,
    reason VARCHAR(30),
    FOREIGN KEY (reason) REFERENCES CLOSURETYPEENUM (closureType)
);