CREATE TABLE ADDRESS (
    id BIGINT NOT NULL,
    city VARCHAR(30),
    street VARCHAR(30),
    house VARCHAR(30),
    PRIMARY KEY (id)
);

CREATE TABLE STORE (
    id BIGINT NOT NULL,
    phone VARCHAR(30),
    name VARCHAR(30),
    address_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES ADDRESS (id)
);

CREATE TABLE IF NOT EXISTS CLOSURETYPEENUM (
    closureType VARCHAR(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS CLOSURE (
    id BIGINT NOT NULL,
    STORE_ID BIGINT,
    text VARCHAR(30),
    START_DATE DATE,
    END_DATE DATE,
    CLOSURE_TYPE VARCHAR(30),
    PRIMARY KEY (id),
    FOREIGN KEY (CLOSURE_TYPE) REFERENCES CLOSURETYPEENUM (closureType)
);

INSERT INTO CLOSURETYPEENUM(closureType) VALUES ('CUSTOM');
INSERT INTO CLOSURETYPEENUM(closureType) VALUES ('WEATHER');
INSERT INTO CLOSURETYPEENUM(closureType) VALUES ('EMERGENCY');

SELECT * FROM CLOSURETYPEENUM;